version: '3.8'

services:
    mysql:
        image: mysql:9.1.0
        container_name: mysql-abiertos
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456789root
            MYSQL_PASSWORD: 123456789root
        volumes:
            - mysql-abiertos:/var/lib/mysql
        networks:
            - sistemasAbiertos

    phpmyadmin:
        image: phpmyadmin5-apache
        container_name: phpmyadmin-abiertos
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql-abiertos
            MYSQL_ROOT_PASSWORD: 123456789root
        networks:
            - sistemasAbiertos

networks:
    sistemasAbiertos:


volumes:
    mysql-abiertos:
